### ISSUE TITLE
Understanding of a method in src/main/java/org/rx/net/http/HttpClient.java

### ISSUE THREAD

**Issue by 129124** [RockyLOMO/rxlib#4]
Hi there, when I was reading the code of the function "public String get(String `url)"` in src/main/java/org/rx/net/http/HttpClient.java, I found it has no Javadoc. My understanding is “get the report for the specified url.@param url the url of the service. @return the value of the allow header". Can you please check if this is correct? Thanks.

**Comment by youfanx** [comment]
yep
